// Manage action
export const GET_ELECTION_PARTY_PANDING = "GET_ELECTION_PARTY_PANDING"
export const GET_ELECTION_PARTY_FULLFILIED = "GET_ELECTION_PARTY_FULLFILIED"
export const GET_ELECTION_PARTY_REJECTED = "GET_ELECTION_PARTY_REJECTED"