// Manage action
export const GET_ELECTION_PARTY_PENDING = "GET_ELECTION_PARTY_PENDING"
export const GET_ELECTION_PARTY_FULLFILIED = "GET_ELECTION_PARTY_FULLFILIED"
export const GET_ELECTION_PARTY_REJECTED = "GET_ELECTION_PARTY_REJECTED"

// add party data
export const POST_ELECTION_PARTY_PENDING = "POST_ELECTION_PARTY_PENDING"
export const POST_ELECTION_PARTY_FULLFILIED = "POST_ELECTION_PARTY_FULLFILIED"
export const POST_ELECTION_PARTY_REJECTED = "POST_ELECTION_PARTY_REJECTED"

// delete party data
export const DELETE_ELECTION_PARTY_PENDING = "DELETE_ELECTION_PARTY_PENDING"
export const DELETE_ELECTION_PARTY_FULLFILIED = "DELETE_ELECTION_PARTY_FULLFILIED"
export const DELETE_ELECTION_PARTY_REJECTED = "DELETE_ELECTION_PARTY_REJECTED"