// Manage action
export const GET_ELECTION_PARTY_PANDING = "GET_ELECTION_PARTY_PANDING"
export const GET_ELECTION_PARTY_FULLFILIED = "GET_ELECTION_PARTY_FULLFILIED"
export const GET_ELECTION_PARTY_REJECTED = "GET_ELECTION_PARTY_REJECTED"

// add party data
export const POST_ELECTION_PARTY_PANDING = "POST_ELECTION_PARTY_PANDING"
export const POST_ELECTION_PARTY_FULLFILIED = "POST_ELECTION_PARTY_FULLFILIED"
export const POST_ELECTION_PARTY_REJECTED = "POST_ELECTION_PARTY_REJECTED"

// delete party data
export const DELETE_ELECTION_PARTY_PANDING = "DELETE_ELECTION_PARTY_PANDING"
export const DELETE_ELECTION_PARTY_FULLFILIED = "DELETE_ELECTION_PARTY_FULLFILIED"
export const DELETE_ELECTION_PARTY_REJECTED = "DELETE_ELECTION_PARTY_REJECTED"